version: "3.7"
services:  
    postgres:
        build:
            context: .
            dockerfile: DockerfilePostgre
        container_name: postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: 123
            PGDATA: /var/lib/postgresql/data/pgdata
        ports: 
            - 5432:5432
        volumes: 
            - pgdata:/var/lib/postgresql/data/pgdata 
        networks: 
            postgres_network:
                aliases: 
                    - postgres_host
    jupyter:
        container_name: notebook
        build: 
            context: .
            dockerfile: DockerfileJupyter
        volumes:
            - ./sql-data/jupyter:/home/jovyan/work
        depends_on: 
            - postgres
        ports:
            - "8888:8888"
volumes: 
    pgdata: {}
networks: 
    postgres_network:
        name: postgres_net
        driver: bridge