version: "3.7"
services:  
    postgres:
        build:
            context: .
            dockerfile: DockerfilePostgre
        container_name: postgres
        restart: always
        environment: 
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
            PGDATA: /var/lib/postgresql/data/pgdata
        ports: 
            - 5432:5432
        volumes: 
            - pgdata:/var/lib/postgresql/data/pgdata 
        networks: 
            postgres_network:
                aliases: 
                    - postgres_host
    dash:
        build:
            context: .
            dockerfile: DockerfileDash
        container_name: dash_dash
        volumes:
            - .:/code
        ports:
            - "80:8080"
        depends_on:
            - postgres
    jupyter:
        container_name: notebook
        build: 
            context: .
            dockerfile: DockerfileJupyter
        volumes:
            - .:/home/jovyan/aaa
        depends_on: 
            - postgres
        ports:
            - "8888:8888"
volumes: 
    pgdata: {}
networks: 
    postgres_network:
        name: postgres_net
        driver: bridge